// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyYVWgd3OMO4l4Q1a4cgRuSFIFTdybcKs',
    appId: '1:146641219486:web:7ac75602a85601deac308f',
    messagingSenderId: '146641219486',
    projectId: 'labproject-a2fda',
    authDomain: 'labproject-a2fda.firebaseapp.com',
    storageBucket: 'labproject-a2fda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqvNtb-j0XDouvnWF04yfAIe1K7KB1E0A',
    appId: '1:146641219486:android:d44c03942b78ba21ac308f',
    messagingSenderId: '146641219486',
    projectId: 'labproject-a2fda',
    storageBucket: 'labproject-a2fda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9cAt6D_QkpKnYYqYNiemFcTwgzsPBsMQ',
    appId: '1:146641219486:ios:0c3603ba384e2cd0ac308f',
    messagingSenderId: '146641219486',
    projectId: 'labproject-a2fda',
    storageBucket: 'labproject-a2fda.appspot.com',
    iosBundleId: 'com.example.newProject4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9cAt6D_QkpKnYYqYNiemFcTwgzsPBsMQ',
    appId: '1:146641219486:ios:0c3603ba384e2cd0ac308f',
    messagingSenderId: '146641219486',
    projectId: 'labproject-a2fda',
    storageBucket: 'labproject-a2fda.appspot.com',
    iosBundleId: 'com.example.newProject4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyYVWgd3OMO4l4Q1a4cgRuSFIFTdybcKs',
    appId: '1:146641219486:web:f137323961e8cdf1ac308f',
    messagingSenderId: '146641219486',
    projectId: 'labproject-a2fda',
    authDomain: 'labproject-a2fda.firebaseapp.com',
    storageBucket: 'labproject-a2fda.appspot.com',
  );
}
